spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/MouJC/config
          username: 847474659@qq.com
          password: tanfu847474
          basedir: /Users/mou/IdeaProjects/Mou/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
