spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 847474659@qq.com
    password: kitjgddghkvjbeeb
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
